services:
  - type: web
    name: pantry-to-plate-backend
    runtime: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn pantrytoplate.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: pantrytoplate.settings_prod
      - key: PYTHON_VERSION
        value: 3.11.8
