from django.urls import path, re_path
from .views import (
    WeeklyMealPlanView,
    RegeneratePlanView,
    UpdateDayView,
    UpdateMealSlotView,
    MenuChangeRequestView,
    MenuChangeRequestResolveView,
    GeneratePlanView,
    GroceryListView,
    ImportGroceryListView,
    PrepareMealView,
    DashboardSummaryView,
    LogWaterView,
    UpdateWeightView,
    CompleteMealView,
    PlanMealView,
    ClearPlanView,
)

urlpatterns = [
    re_path(r'^week/?$', WeeklyMealPlanView.as_view(), name='mealplan-week'),
    re_path(r'^regenerate/?$', RegeneratePlanView.as_view(), name='mealplan-regenerate'),
    re_path(r'^generate/?$', GeneratePlanView.as_view(), name='mealplan-generate'),
    re_path(r'^plan/?$', PlanMealView.as_view(), name='mealplan-plan'),
    re_path(r'^plan/(?P<plan_id>[^/]+)/?$', ClearPlanView.as_view(), name='mealplan-clear'),
    re_path(r'^grocery-list/?$', GroceryListView.as_view(), name='mealplan-grocery-list'),
    re_path(r'^grocery-list/import/?$', ImportGroceryListView.as_view(), name='mealplan-import-grocery-list'),
    re_path(r'^prepare-meal/?$', PrepareMealView.as_view(), name='mealplan-prepare-meal'),
    re_path(r'^day/(?P<day>[^/]+)/?$', UpdateDayView.as_view(), name='mealplan-update-day'),
    re_path(r'^meal/?$', UpdateMealSlotView.as_view(), name='mealplan-update-meal'),
    re_path(r'^menu-request/?$', MenuChangeRequestView.as_view(), name='menu-change-request'),
    re_path(r'^menu-requests/?$', MenuChangeRequestView.as_view(), name='menu-change-requests'),
    re_path(r'^menu-request/(?P<request_id>[^/]+)/resolve/?$', MenuChangeRequestResolveView.as_view(), name='menu-change-resolve'),
    re_path(r'^dashboard-summary/?$', DashboardSummaryView.as_view(), name='dashboard-summary'),
    re_path(r'^log-water/?$', LogWaterView.as_view(), name='log-water'),
    re_path(r'^update-weight/?$', UpdateWeightView.as_view(), name='update-weight'),
    re_path(r'^complete-meal/?$', CompleteMealView.as_view(), name='complete-meal'),
]
